# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CanNotExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry'
pod 'AFNetworking', '~> 3.0'
pod 'SVProgressHUD'
#pod 'MLeaksFinder'
pod 'SDCycleScrollView','~> 1.75'
pod 'MJExtension'
pod 'SDWebImage', '~> 4.0'
pod 'TZImagePickerController'
pod 'MJRefresh'
pod 'ReactiveObjC', '~> 3.1.0'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'MMKV'
  # Pods for CanNotExtension

  target 'CanNotExtensionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CanNotExtensionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
