# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftAlamofire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftAlamofire
pod 'Alamofire', '~> 5.0.0-beta.6'
end
